const autoSuggestion = [
    "1password",
    "3d",
    "3d Reconstruction",
    "Aboutness",
    "Abstract Data Type",
    "Abstract Interpretation",
    "Abstract Machine",
    "Access Control",
    "Access Method",
    "Access Network",
    "Accounting",
    "Active Appearance Model",
    "Active Database",
    "Active Networking",
    "Active Shape Model",
    "Activemq",
    "Activity Recognition",
    "Actuarial Science",
    "Actuator",
    "Adaboost",
    "Adaptive Routing",
    "Adaptive System",
    "Adder",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Advertising",
    "Aerial Photography",
    "Aeronautics",
    "Aerospace Engineering",
    "Aerospike",
    "Agile Project Management",
    "Agricultural Engineering",
    "Airflow",
    "Airtable",
    "Ajax",
    "Akamai",
    "Akka",
    "Algolia",
    "Algorithm",
    "Algorithm Design",
    "Alpine Linux",
    "Amazon Api Gateway",
    "Amazon Athena",
    "Amazon Cloudfront",
    "Amazon Cloudwatch",
    "Amazon Cognito",
    "Amazon Dynamodb",
    "Amazon Ebs",
    "Amazon Ec2",
    "Amazon Ec2 Container service",
    "Amazon Eks",
    "Amazon Elasticache",
    "Amazon Elasticsearch Service",
    "Amazon Emr",
    "Amazon Kinesis",
    "Amazon Kinesis Firehose",
    "Amazon Machine Learning",
    "Amazon Rds",
    "Amazon Rds For aurora",
    "Amazon Rds For postgresql",
    "Amazon Redshift",
    "Amazon Route 53",
    "Amazon S3",
    "Amazon Ses",
    "Amazon Sns",
    "Amazon Sqs",
    "Amazon Vpc",
    "Ambiguity",
    "Amphp",
    "Amplitude",
    "Analog To Digital converter",
    "Analysis Of Algorithms",
    "Analysis Of Covariance",
    "Analysis Of Variance",
    "Analytics",
    "Analytics Integrator",
    "Android",
    "Android Sdk",
    "Android Studio",
    "Angular",
    "Angular 2",
    "AngularJs",
    "AngularUI",
    "Anomaly Detection",
    "Ansible",
    "Ant Design",
    "Apache Ant",
    "Apache Cordova",
    "Apache Flink",
    "Apache Http Server",
    "Apache Maven",
    "Apache Mesos",
    "Apache Spark",
    "Apache Tomcat",
    "Apache Zeppelin",
    "Api",
    "Api Documentation Browser",
    "Api Tools",
    "Api.Ai",
    "Apiary",
    "Apigee",
    "Apollo",
    "Appium",
    "Application And Data",
    "Application Hosting",
    "Application Programming Interface",
    "Application Server",
    "Application Specific Integrated circuit",
    "Application Utilities",
    "Appveyor",
    "Arangodb",
    "Arbol",
    "Arboriculture",
    "Arborist",
    "Arch Linux",
    "Architectural Engineering",
    "Arduino",
    "Art Architecture Thesaurus",
    "Artificial Intelligence",
    "Artificial Neural Network",
    "Asana",
    "Asp.Net",
    "Aspect Oriented Programming",
    "Aspnet",
    "Assets And Media",
    "Association Rule Learning",
    "Asynchronous Communication",
    "Asynchronous Transfer Mode",
    "Atom",
    "Audio Signal",
    "Augmented Reality",
    "Aurelia",
    "Auth0",
    "Authentication",
    "Authy",
    "Automated Reasoning",
    "Automated Theorem Proving",
    "Automatic Programming",
    "Automatic Summarization",
    "Automatic Taxonomy Induction",
    "Automaton",
    "Automotive Engineering",
    "Autonomic Computing",
    "Ava",
    "Awesome",
    "Aws",
    "Aws Cloudformation",
    "Aws Codebuild",
    "Aws Codecommit",
    "Aws Codedeploy",
    "Aws Codepipeline",
    "Aws Direct Connect",
    "Aws Elastic Beanstalk",
    "Aws Elastic Load balancing elb",
    "Aws Fargate",
    "Aws Iam",
    "Aws Lambda",
    "Aws Opsworks",
    "Awx",
    "Azure",
    "Azure Cosmos Db",
    "Azure Functions",
    "Azure Machine Learning",
    "Azure Storage",
    "Azure Websites",
    "Babel",
    "Back Office",
    "Backbone.Js",
    "Background Processing",
    "Background Subtraction",
    "Bag Of Words model",
    "Bamboo",
    "Base Station",
    "Bash",
    "Batch Processing",
    "Bayesian Inference",
    "Bayesian Network",
    "Bayesian Probability",
    "Bazel",
    "Beanstalk",
    "Beanstalkd",
    "Benchmark Computing",
    "Beta By Crashlytics",
    "Beta Testing Mobile app distribution",
    "Bibliographic Database",
    "Bibliometrics",
    "Big Data",
    "Big Data As a service",
    "Big Data Tools",
    "Binary Search Tree",
    "Biochemical Engineering",
    "Biological Database",
    "Biomedical Engineering",
    "Biometrics",
    "Bitbucket",
    "Bitcoin",
    "Bitrise",
    "Blind Signal Separation",
    "Blockchain",
    "Body Text",
    "Boolean Algebra",
    "Boolean Expression",
    "Boosting Machine Learning",
    "Boot2docker",
    "Bootstrap",
    "Bootswatch",
    "Bot",
    "Bourbon",
    "Bower",
    "Box",
    "Brackets",
    "Brain Mapping",
    "Braintree",
    "Branch And Bound",
    "Breadth First Search",
    "Brightness",
    "Broadcasting",
    "Browser Testing",
    "Browserify",
    "Browserstack",
    "Browsersync",
    "Brunch",
    "Brute Force Search",
    "Buddy",
    "Buffer",
    "Buffer Overflow",
    "Build Test Deploy",
    "Buildkite",
    "Built In Self test",
    "Bulma",
    "Business",
    "Business Administration",
    "Business Dashboards",
    "Business Intelligence",
    "Business Process",
    "Business Tools",
    "c",
    "C3.Js",
    "Caddy",
    "Cakephp",
    "Canonical Correlation",
    "Canonical Model",
    "Capistrano",
    "Capybara",
    "Case Based Reasoning",
    "Cassandra",
    "Cataloging",
    "Cdnjs",
    "Celery",
    "Cellular Network",
    "Centos",
    "Central Processing Unit",
    "Cepstrum",
    "Certificate",
    "Certificate Authority",
    "Change Detection",
    "Chartbeat",
    "Charting Libraries",
    "Chatbot Platforms Tools",
    "Chatops",
    "Chef",
    "Chemical Engineering",
    "Chemometrics",
    "Chrome",
    "Chrome Extension",
    "Circleci",
    "Circumscription",
    "Civil Engineering",
    "Classical Logic",
    "Classifier Linguistics",
    "Clef",
    "Clever Cloud",
    "Cli",
    "Clicktale",
    "Clicky",
    "Clientserver Model",
    "Clinicalkey",
    "Clion",
    "Clojure",
    "Clojurescript",
    "Clone Java Method",
    "Cloud Access Management",
    "Cloud Content Management system",
    "Cloud Firestore",
    "Cloud Foundry",
    "Cloud Functions For firebase",
    "Cloud Hosting",
    "Cloud Ide",
    "Cloud Monitoring",
    "Cloud Storage",
    "Cloud9 Ide",
    "Cloudflare",
    "Cloudinary",
    "Clubhouse",
    "Cluster Analysis",
    "Cluster Management",
    "Cobol",
    "Cocoa Touch Ios",
    "Codacy",
    "Code Climate",
    "Code Collaboration Version control",
    "Code Coverage",
    "Code Generation",
    "Code Quality",
    "Code Review",
    "Codeanywhere",
    "Codebook",
    "Codec",
    "Codecov",
    "Codeigniter",
    "Codekit",
    "Codemirror",
    "Codenvy",
    "Codeship",
    "Coding Social Sciences",
    "Coffeescript",
    "Cognitive Neuroscience Of visual object recognition",
    "Collaboration",
    "Collision",
    "Color Vision",
    "Colorimetry",
    "Combinatorial Optimization",
    "Commenting Service",
    "Commerce",
    "Common Object Request broker architecture",
    "Communication Complexity",
    "Communication In Small groups",
    "Communications",
    "Communications Protocol",
    "Communications Sdk",
    "Communications System",
    "Compass",
    "Compiler",
    "Complex Data Type",
    "Complex System",
    "Component",
    "Component Analysis",
    "Compose",
    "Composer",
    "Composite Index",
    "Composite Number",
    "Comprehension",
    "Compressed Sensing",
    "Computability",
    "Computability Theory",
    "Computation",
    "Computational Complexity Theory",
    "Computational Geometry",
    "Computational Mathematics",
    "Computational Model",
    "Computational Science",
    "Computer Aided Software engineering",
    "Computer Architecture",
    "Computer Cluster",
    "Computer Data Storage",
    "Computer Engineering",
    "Computer File",
    "Computer Graphics",
    "Computer Graphics Images",
    "Computer Hardware",
    "Computer Multitasking",
    "Computer Network",
    "Computer Program",
    "Computer Programming",
    "Computer Science",
    "Computer Security",
    "Computer Vision",
    "Concept Learning",
    "Conceptual Model",
    "Concourse",
    "Concurrency",
    "Concurrency Control",
    "Concurrency Frameworks",
    "Concurrent Computing",
    "Conditional Random Field",
    "Conductor",
    "Confirmatory Factor Analysis",
    "Confluence",
    "Consistency Model",
    "Constant False Alarm rate",
    "Construction Engineering",
    "Consul",
    "Container Tools",
    "Containers As A service",
    "Content Delivery Network",
    "Content Management",
    "Context Free Language",
    "Contextual Query Language",
    "Contingency Table",
    "Continuous Deployment",
    "Continuous Integration",
    "Continuum Design Consultancy",
    "Control Engineering",
    "Control Flow",
    "Control Reconfiguration",
    "Control Theory",
    "Controlled Vocabulary",
    "Conventional Pci",
    "Convergence Routing",
    "Coordinate System",
    "Copy Protection",
    "Core Network",
    "Coreos",
    "Corner Detection",
    "Correctness",
    "Correlation Coefficient",
    "Cost Database",
    "Couchbase",
    "Couchdb",
    "Coveralls",
    "Cpp",
    "Cranfield Experiments",
    "Crashlytics",
    "Crazy Egg",
    "Create React App",
    "Create React Native app",
    "Critical Mass Software engineering",
    "Critical Path Method",
    "Critical Section",
    "Crm",
    "Cross Correlation",
    "Cross Platform Desktop development",
    "Cross Platform Mobile development",
    "Cross Platform Mobile tools",
    "Cross Validation",
    "Crowdsourcing",
    "Cryptocurrency",
    "Cryptographic Protocol",
    "Cryptography",
    "Crystal",
    "Csharp",
    "Css",
    "Css Pre Processors extensions",
    "Cucumber",
    "Curse Of Dimensionality",
    "Curve Fitting",
    "Custom Analytics",
    "Customer Analytics",
    "Customer Relationship Management",
    "Customer Support Chat",
    "Cypress",
    "D3.Js",
    "Dart",
    "Dash",
    "Data Access",
    "Data Acquisition",
    "Data Analysis",
    "Data As A service",
    "Data Center",
    "Data Classification",
    "Data Compression",
    "Data Consistency",
    "Data Cube",
    "Data Exchange",
    "Data Extraction",
    "Data File",
    "Data Flow Diagram",
    "Data Integration",
    "Data Integrity",
    "Data Logger",
    "Data Management",
    "Data Manipulation Language",
    "Data Mining",
    "Data Model",
    "Data Modeling",
    "Data Pre Processing",
    "Data Processing",
    "Data Quality",
    "Data Reduction",
    "Data Retrieval",
    "Data Science",
    "Data Science Notebooks",
    "Data Science Tools",
    "Data Sharing",
    "Data Stores",
    "Data Stream",
    "Data Stream Mining",
    "Data Structure",
    "Data Structures",
    "Data System",
    "Data Transmission",
    "Data Type",
    "Data Validation",
    "Data Visualization",
    "Data Warehouse",
    "Database",
    "Database Design",
    "Database Security",
    "Database Tools",
    "Database Transaction",
    "Databases",
    "Datadog",
    "Datalog",
    "Dcos",
    "Deadlock",
    "Debian",
    "Debugging",
    "Decidability",
    "Decision Problem",
    "Decision Rule",
    "Decision Support System",
    "Decision Tree",
    "Deco",
    "Decomposition Method Constraint satisfaction",
    "Dedicated Cloud Hosting",
    "Deductive Database",
    "Deep Learning",
    "Dempstershafer Theory",
    "Denial Of Service attack",
    "Deontic Logic",
    "Dependency Management",
    "Dependency Monitoring",
    "Deploybot",
    "Deployment",
    "Deployment As A service",
    "Description Logic",
    "Design",
    "Design For Testing",
    "Detection Theory",
    "Deterministic Automaton",
    "Devdocs",
    "Devise",
    "Devops",
    "Diagram",
    "Digital Filter",
    "Digital Radio",
    "Digital Signal Processing",
    "Digital Signature",
    "Digital Subscriber Line",
    "Digitalocean",
    "Dijkstras Algorithm",
    "Dimensionality Reduction",
    "Directed Graph",
    "Discrete Cosine Transform",
    "Discrete Event Simulation",
    "Discrete Logarithm",
    "Discrete System",
    "Discriminative Model",
    "Disjunctive Normal Form",
    "Display Device",
    "Disqus",
    "Distance Transform",
    "Distributed Algorithm",
    "Distributed Computing",
    "Distributed Computing Environment",
    "Distributed Data Store",
    "Distributed Database",
    "Distributed File System",
    "Distributed Memory",
    "Distributed Object",
    "Divide And Conquer algorithms",
    "Django",
    "Django Rest Framework",
    "Dns Management",
    "Dnsimple",
    "Docker",
    "Docker Cloud",
    "Docker Compose",
    "Docker For Aws",
    "Docker Machine",
    "Docker Swarm",
    "Doctrine 2",
    "Document Classification",
    "Document Collaboration",
    "Document Layout Analysis",
    "Document Management System",
    "Document Processing",
    "Document Retrieval",
    "Document Signature",
    "Documentation",
    "Documentation As A service tools",
    "Dokku",
    "Domain Knowledge",
    "Domain Model",
    "Domain Registration",
    "Dotnet",
    "Drone.Io",
    "Dropbox",
    "Dropwizard",
    "Druid",
    "Drupal",
    "Duplicate Content",
    "Durability",
    "Dyn",
    "Dynamic Data",
    "Dynamic Loading",
    "Dynamic Programming",
    "Dynamic Range",
    "Dynamic Source Routing",
    "Dynamic Testing",
    "Dynamic Time Warping",
    "Echo",
    "Eclipse",
    "Ecommerce",
    "Econometric Model",
    "Economic Policy",
    "Edit Distance",
    "Elasticsearch",
    "Electrical Engineering",
    "Electroencephalography",
    "Electron",
    "Electronic Data Interchange",
    "Electronic Document",
    "Electronic Engineering",
    "Elixir",
    "Elm",
    "Emacs",
    "Email Marketing",
    "Email Testing",
    "Embedded System",
    "Ember",
    "Ember.Js",
    "Emoji",
    "Emotion",
    "Emotion Recognition",
    "Emulator",
    "Encoding Memory",
    "Encryption",
    "Engagementlifecycle Marketing",
    "Engineering",
    "Engineering Drawing",
    "Engineering Ethics",
    "Ensemble Learning",
    "Enterprise Information Security architecture",
    "Enterprise System",
    "Entityrelationship Model",
    "Environmental Engineering",
    "Enzyme",
    "Erasure Code",
    "Erlang",
    "Error Concealment",
    "Error Detection And correction",
    "Errors In Variables models",
    "Es6",
    "Eslint",
    "Espace",
    "Etcd",
    "Ethereum",
    "Ethernet",
    "Euclidean Distance",
    "Eureka",
    "Evolutionary Algorithm",
    "Exact Algorithm",
    "Exception Monitoring",
    "Expander Graph",
    "Expectationmaximization Algorithm",
    "Expert System",
    "Exploratory Data Analysis",
    "Expressjs",
    "External Data Representation",
    "Eye Movement",
    "Eye Tracking",
    "f",
    "Fabric",
    "Fabric By Twitter",
    "Faceted Classification",
    "Faceted Search",
    "Facial Expression",
    "Facial Recognition System",
    "Factorial Experiment",
    "False Positive Rate",
    "Fast Fourier Transform",
    "Fastlane",
    "Fastly",
    "Fault Model",
    "Fault Tolerance",
    "Feathersjs",
    "Feature Detection",
    "Feature Extraction",
    "Feature Selection",
    "Feature Vector",
    "Fedora",
    "Ffmpeg",
    "Field Of View",
    "Field Programmable Gate array",
    "Figma",
    "Figure Of Merit",
    "File Format",
    "File Storage",
    "File System",
    "File Uploads",
    "Filestack",
    "Filter Signal Processing",
    "Finagle",
    "Finance",
    "Financial System",
    "Findability",
    "Fingerprint",
    "Fingerprint Recognition",
    "Finite State Machine",
    "Firebase",
    "Firefox",
    "First Class",
    "First Order Logic",
    "Flash Memory",
    "Flask",
    "Flat Panel Display",
    "Flip Flop",
    "Floating Point",
    "Flow Control Data",
    "Flow Type",
    "Fluentd",
    "Flurry",
    "Flutter",
    "Flux",
    "Flyway",
    "Folksonomy",
    "Font",
    "Forensic Engineering",
    "Formal Concept Analysis",
    "Formal Language",
    "Formal Methods",
    "Formal Specification",
    "Formal Verification",
    "Fortran",
    "Forums",
    "Fossa",
    "Fragmentation Computing",
    "Framer",
    "Framework",
    "Framework7",
    "Frameworks Full Stack",
    "Frequency Analysis",
    "Frequency Domain",
    "Front And Back ends",
    "Front End Frameworks",
    "Front End Package manager",
    "Frontend",
    "Fullstory",
    "Functional Dependency",
    "Functional Programming",
    "Functional Testing",
    "Funnel Analysis Analytics",
    "Fusion",
    "Fuzzy Logic",
    "G Suite",
    "Game Development",
    "Game Engine",
    "Garbage Collection",
    "Gatling",
    "Gatsby",
    "Gauges",
    "Gaussian Noise",
    "Gaussian Process",
    "Gearman",
    "Geckoboard",
    "General Analytics",
    "Generalization Error",
    "Generalized Linear Model",
    "Genetic Algorithm",
    "Geographic Information Retrieval",
    "Geometric Modeling",
    "Geoparsing",
    "Geospatial Analysis",
    "Geotagging",
    "Geotechnical Engineering",
    "Gerrit Code Review",
    "Gist",
    "Git",
    "Git Tools",
    "Gitbucket",
    "Github",
    "Github Api",
    "Github Enterprise",
    "Github Pages",
    "Gitkraken",
    "Gitlab",
    "Gitlab Ci",
    "Gitlab Pages",
    "Gluon",
    "Gnu Bash",
    "Go",
    "Go.Cd",
    "Godaddy",
    "Gogs",
    "Goodness Of Fit",
    "Google",
    "Google Analytics",
    "Google App Engine",
    "Google App Maker",
    "Google Bigquery",
    "Google Cloud Bigtable",
    "Google Cloud Container builder",
    "Google Cloud Dataflow",
    "Google Cloud Datastore",
    "Google Cloud Dns",
    "Google Cloud Functions",
    "Google Cloud Memorystore",
    "Google Cloud Messaging",
    "Google Cloud Pubsub",
    "Google Cloud Sql",
    "Google Cloud Storage",
    "Google Cloud Vision api",
    "Google Compute Engine",
    "Google Drive",
    "Google Kubernetes Engine",
    "Google Maps",
    "Google Scholar And academic libraries",
    "Google Sheets",
    "Google Tag Manager",
    "Gradient Descent",
    "Gradle",
    "Grafana",
    "Grails",
    "Grape",
    "Graph Databases",
    "Graphic Design",
    "Graphical Model",
    "Graphical User Interface",
    "Graphite",
    "Graphql",
    "Greedy Algorithm",
    "Groovy",
    "Ground Truth",
    "Group Chat Notifications",
    "Growbag",
    "Grpc",
    "Grunt",
    "Gsm",
    "Gtp",
    "Gulp",
    "Gunicorn",
    "Guzzle",
    "Hadoop",
    "Haml",
    "Handlebars.Js",
    "Handover",
    "Hapi",
    "Haproxy",
    "Haptic Technology",
    "Hash Function",
    "Haskell",
    "Hasura",
    "Hazelcast",
    "Hbase",
    "Headless Browsers",
    "Heap",
    "Heap Data Structure",
    "Heatmap Analytics",
    "Helm",
    "Help Desk",
    "Heroku",
    "Heroku Ci",
    "Heroku Postgres",
    "Heroku Redis",
    "Hetzner Online Ag",
    "Hexo",
    "Hhvm Hiphop Virtual machine",
    "Hibernate",
    "Hidden Markov Model",
    "Hierarchical Database Model",
    "High Availability",
    "High Level Programming language",
    "High Level Synthesis",
    "Highcharts",
    "Higher Order Statistics",
    "Hilberthuang Transform",
    "Hipchat",
    "Histogram",
    "Hockeyapp",
    "Hogan.Js",
    "Homebrew",
    "Homebridge",
    "Homogeneity Statistics",
    "Hosted Blogging Platforms",
    "Hotjar",
    "Hough Transform",
    "Html",
    "Html5",
    "Http",
    "Hubspot",
    "Hugo",
    "Human Visual System model",
    "Humancomputer Information Retrieval",
    "Humancomputer Interaction",
    "Hybrid Algorithm",
    "Hybrid System",
    "Hypercube",
    "Hyperspectral Imaging",
    "Ibm Api Connect",
    "Ibm Db2",
    "Icon Font",
    "Iframely",
    "Ifttt",
    "Image Analysis Api",
    "Image Fusion",
    "Image Meta Search",
    "Image Processing",
    "Image Processing And management",
    "Image Quality",
    "Image Registration",
    "Image Resolution",
    "Image Retrieval",
    "Image Segmentation",
    "Image Sensor",
    "Imgix",
    "Immutable.Js",
    "Impala",
    "In Memory Databases",
    "Incapsula",
    "Incremental Learning",
    "Indentation",
    "Independent Component Analysis",
    "Independent Set",
    "Index Term",
    "Industrial Engineering",
    "Industrial Organization",
    "Inference",
    "Influxdb",
    "Infobox",
    "Information Discovery",
    "Information Extraction",
    "Information Filtering System",
    "Information Flow Information theory",
    "Information Integration",
    "Information Management",
    "Information Model",
    "Information Overload",
    "Information Retrieval",
    "Information Retrieval Applications",
    "Information Retrieval Query language",
    "Information Seeking",
    "Information Theory",
    "Infrastructure Build Tools",
    "Inkwell",
    "Input Device",
    "Insomnia Rest Client",
    "Inspec",
    "Instrumental Variable",
    "Integer Programming",
    "Integrated Circuit Design",
    "Integrated Development Environment",
    "Integrated Development Environment tools",
    "Integrated Services Digital network",
    "Intelligent Agent",
    "Intelligent Document",
    "Intelligent Network",
    "Intellij Idea",
    "Inter Process Communication",
    "Interaction",
    "Interactive Mockups",
    "Intercom",
    "Interconnection",
    "International Trade",
    "Internet Of Things",
    "Internet Of Things hardware",
    "Internet Privacy",
    "Internet Protocol Suite",
    "Internetworking",
    "Interpolation",
    "Intrusion Detection System",
    "Intuitionistic Logic",
    "Invision",
    "Ionic",
    "Ios",
    "Ipfs",
    "Ir Evaluation",
    "Issue Tracking",
    "Istio",
    "Iterative Reconstruction",
    "Jasmine",
    "Java",
    "Java Build Tools",
    "Javascript",
    "Javascript Framework Components",
    "Javascript Mvc Frameworks",
    "Javascript Testing Framework",
    "Javascript Ui Libraries",
    "Javascript Utilities Libraries",
    "Jekyll",
    "Jenkins",
    "Jest",
    "Jetty",
    "Jira",
    "Jitter",
    "Jquery",
    "Jquery Mobile",
    "Jquery Ui",
    "Jruby",
    "Js Build Tools js task runners",
    "Jsdoc",
    "Json",
    "Json Server",
    "Julia",
    "Junit",
    "Jupyter",
    "Jupyter Notebook",
    "K D tree",
    "K Nearest Neighbors algorithm",
    "Kafka",
    "Kalman Filter",
    "Kanban For Github issues",
    "Kanban Tool",
    "Karhunenlove Theorem",
    "Karma",
    "Kendo Ui",
    "Keras",
    "Kernel Linear Algebra",
    "Key Exchange",
    "Key Lock",
    "Keycdn",
    "Keyword Extraction",
    "Kibana",
    "Kissmetrics",
    "Kitematic",
    "Knapsack Problem",
    "Knex.Js",
    "Knockoutjs",
    "Knowledge Acquisition",
    "Knowledge Base",
    "Knowledge Based Systems",
    "Knowledge Extraction",
    "Knowledge Management",
    "Knowledge Modeling",
    "Knowledge Representation And reasoning",
    "Knowledge Retrieval",
    "Koa",
    "Koding",
    "Kong",
    "Kotlin",
    "Kubernetes",
    "Kullbackleibler Divergence",
    "Lambda Calculus",
    "Lambdatest",
    "Landing Pages",
    "Language Acquisition",
    "Language Model",
    "Languages",
    "Languages Frameworks",
    "Laravel",
    "Laravel Forge",
    "Laravel Homestead",
    "Lastpass",
    "Latency Engineering",
    "Latent Dirichlet Allocation",
    "Latent Semantic Indexing",
    "Latex",
    "Layout Engine",
    "Leaflet",
    "Least Squares",
    "Legal Information Retrieval",
    "Less",
    "Lets Encrypt",
    "Level Of Detail",
    "Level Set",
    "Lexico",
    "Libraries",
    "Library",
    "Library Science",
    "Line Of Sight",
    "Linear Discriminant Analysis",
    "Linear Logic",
    "Linear Model",
    "Linear Prediction",
    "Linear Programming",
    "Linear Regression",
    "Linear Search",
    "Linear Temporal Logic",
    "Link Analysis",
    "Link Layer",
    "Link Relation",
    "Linked Data",
    "Linode",
    "Linux",
    "Linux Mint",
    "Liquibase",
    "Liquid Crystal Display",
    "Live Reloading",
    "Livereload",
    "Load And Performance testing",
    "Load Balancer Reverse proxy",
    "Load Balancing Computing",
    "Load Management",
    "Loader.Io",
    "Local Area Network",
    "Local Search Optimization",
    "Localhost Tools",
    "Localization",
    "Location Based Service",
    "Locust",
    "Lodash",
    "Log Management",
    "Loggly",
    "Logic Gate",
    "Logic In Computer science",
    "Logic Programming",
    "Logic Synthesis",
    "Logical Framework",
    "Logistic Regression",
    "Logrocket",
    "Logstash",
    "Look Ahead",
    "Lookup Table",
    "Lottie",
    "Low Pass Filter",
    "Lua",
    "Lucene",
    "Lumen",
    "Lxc",
    "Lxd",
    "Machine Learning",
    "Machine Learning As a service",
    "Machine Learning Tools",
    "Machine Vision",
    "Macos",
    "Magento",
    "Mailchimp",
    "Mailgun",
    "Mailjet",
    "Managed Memcache",
    "Management Science",
    "Mandrill",
    "Manufacturing Engineering",
    "Mapbox",
    "Mapping Apis",
    "Marathon",
    "Mariadb",
    "Marine Engineering",
    "Marionette",
    "Markdown",
    "Marketing",
    "Marketing Automation",
    "Markov Chain",
    "Markup Language",
    "Mastodon",
    "Matched Filter",
    "Material",
    "Material Design",
    "Material Design For angular",
    "Material Design For bootstrap",
    "Material Design Lite",
    "Material Ui",
    "Materialize",
    "Mathematical Logic",
    "Matlab",
    "Mattermost",
    "Maven",
    "Maxcdn",
    "Maximum A posteriori Estimation",
    "Mean",
    "Mean Shift",
    "Mechanical Engineering",
    "Media Access Control",
    "Medical Imaging",
    "Medical Literature Retrieval",
    "Medium",
    "Memcached",
    "Memcachier",
    "Memory Management",
    "Mercurial",
    "Mesh Networking",
    "Mesosphere",
    "Message Passing",
    "Message Queue",
    "Messenger Platform",
    "Metabase",
    "Metadata",
    "Metamodeling",
    "Meteor",
    "Metis",
    "Microcomputer",
    "Microcontroller",
    "Microdata Html",
    "Microframeworks Backend",
    "Microprocessor",
    "Microservices Tools",
    "Microsoft Azure",
    "Microsoft Bot Framework",
    "Microsoft Iis",
    "Microsoft Sql Server",
    "Middleman",
    "Middleware",
    "Mina",
    "Minecraft",
    "Minification",
    "Mining Engineering",
    "Minio",
    "Missing Data",
    "Mixed Model",
    "Mixpanel",
    "Mixture Model",
    "Ml Kit",
    "Mobile",
    "Mobile Agent",
    "Mobile Analytics",
    "Mobile Backend",
    "Mobile Computing",
    "Mobile Continuous Integration",
    "Mobile Database",
    "Mobile Error Monitoring",
    "Mobile Prototyping Interaction design tools",
    "Mobile Push Messaging",
    "Mobile Radio",
    "Mobile Robot",
    "Mobile Station",
    "Mobile Telephony",
    "Mobile Testing Frameworks",
    "Mobile Ui Frameworks",
    "Mobility Management",
    "Mobility Model",
    "Mobx",
    "Mocha",
    "Modal Logic",
    "Mode",
    "Model Based Reasoning",
    "Model Checking",
    "Modular Design",
    "Momentjs",
    "Monero",
    "Mongodb",
    "Mongodb Atlas",
    "Mongodb Hosting",
    "Mongodb Stitch",
    "Mongoid",
    "Mongolab",
    "Mongoose",
    "Monitoring",
    "Monitoring Aggregation",
    "Monitoring Tools",
    "Morphology Linguistics",
    "Motion Analysis",
    "Motion Compensation",
    "Motion Detection",
    "Motion Estimation",
    "Motion Planning",
    "Moving Average",
    "Multi Agent System",
    "Multi Core Processor",
    "Multi Objective Optimization",
    "Multi User",
    "Multicast",
    "Multidimensional Analysis",
    "Multidimensional Scaling",
    "Multilevel Model",
    "Multimedia",
    "Multimedia Database",
    "Multimodal Search",
    "Multiprocessing",
    "Multisearch",
    "Multispectral Image",
    "Multivariate Analysis",
    "Multivariate Statistics",
    "Mustache",
    "Mutual Exclusion",
    "Mutual Information",
    "Mvc Tools",
    "Mvvmcross",
    "Mysql",
    "Naive Bayes Classifier",
    "Namecheap",
    "Named Entity",
    "Nativescript",
    "Nats",
    "Natural Deduction",
    "Natural Language",
    "Natural Language Processing",
    "Natural Language Understanding",
    "Navigation System",
    "Neo4j",
    "Neovim",
    "Netbeans Ide",
    "Netlify",
    "Netty",
    "Network Architecture",
    "Network Congestion",
    "Network Delay",
    "Network Interface",
    "Network Layer",
    "Network Management",
    "Network Model",
    "Network Performance",
    "Network Planning And design",
    "Network Security",
    "Network Simulation",
    "Network Topology",
    "Neural Coding",
    "New Relic",
    "Nexmo",
    "Next Generation Network",
    "Next.Js",
    "Nginx",
    "Ngrok",
    "Nightwatchjs",
    "Nim",
    "Nitrous.Io",
    "Node Networking",
    "Node.Js",
    "Node.Js Process manager",
    "Nodejs",
    "Noise Measurement",
    "Noise Reduction",
    "Noisy Data",
    "Nomad",
    "Non Volatile Memory",
    "Nosql",
    "Nosql Database As a service",
    "Notepad",
    "Npm",
    "Nsq",
    "Nuclear Engineering",
    "Numerical Stability",
    "Numpy",
    "Nuxt",
    "Object Detection",
    "Object Document Mapper odm",
    "Object Model",
    "Object Oriented Programming",
    "Object Relational Mapper orm",
    "Objective C",
    "Octodns",
    "Octopus Deploy",
    "Omniauth",
    "Onesignal",
    "Online Algorithm",
    "Online Public Access catalog",
    "Onsen Ui",
    "Ontology Information Science",
    "Open Data",
    "Open Postgresql Monitoring",
    "Open Source Cloud",
    "Open Source Service discovery",
    "Opencv",
    "Opengl",
    "Openlayers",
    "Openresty",
    "Openshift",
    "Openstack",
    "Opensuse",
    "Operating System",
    "Operating Systems",
    "Operational Transformation",
    "Operations Management",
    "Operations Research",
    "Operator Computer Programming",
    "Optical Character Recognition",
    "Optical Disc",
    "Optical Flow",
    "Optical Imaging",
    "Optical Recording",
    "Optical Transfer Function",
    "Optimization Problem",
    "Optimizely",
    "Oracle",
    "Outlier",
    "Overlay Network",
    "Ovh",
    "Oxygene",
    "P System",
    "P2p",
    "Package Manager",
    "Package Managers",
    "Packer",
    "Pandas",
    "Parallel Algorithm",
    "Parallel Computing",
    "Parcel",
    "Parse",
    "Parse Server",
    "Parsing",
    "Particle Filter",
    "Particle Swarm Optimization",
    "Passenger",
    "Passive Optical Network",
    "Password Management",
    "Patent Classification",
    "Patent Visualisation",
    "Path Analysis Statistics",
    "Pattern Matching",
    "Pattern Recognition",
    "Pattern Recognition Psychology",
    "Paw",
    "Payment Services",
    "Payments",
    "Paypal",
    "Peak Signal To noise ratio",
    "Peer To Peer",
    "Performance Metric",
    "Performance Monitoring",
    "Performance Prediction",
    "Perl",
    "Perl6",
    "Persistence Computer Science",
    "Petri Net",
    "Petroleum Engineering",
    "Phabricator",
    "Phalcon",
    "Phantomjs",
    "Phaser",
    "Phoenix Framework",
    "Phonegap",
    "Photogrammetry",
    "Php",
    "Php Mvc",
    "Phpstorm",
    "Phpunit",
    "Pico 8",
    "Pile",
    "Pingdom",
    "Piwik",
    "Pixel",
    "Pixel Art",
    "Plagiarism Detection",
    "Platform As A service",
    "Platform As A service tools",
    "Play",
    "Plotly",
    "Point Location",
    "Point Spread Function",
    "Point To Point",
    "Polymer",
    "Polymorphism Computer Science",
    "Port Computer Networking",
    "Portainer",
    "Pose",
    "Postcss",
    "Postgis",
    "Postgresql",
    "Postgresql As A service",
    "Postman",
    "Postmark",
    "Pouchdb",
    "Power Control",
    "Power Management",
    "Preact",
    "Precision And Recall",
    "Predictive Coding",
    "Predictive Value Of tests",
    "Presentation Semantics",
    "Prestashop",
    "Presto",
    "Principal Component Analysis",
    "Prisma",
    "Process Calculus",
    "Process Engineering",
    "Process Management",
    "Prognostics",
    "Program Analysis",
    "Program Design Language",
    "Program Optimization",
    "Program Synthesis",
    "Program Transformation",
    "Programmable Logic Device",
    "Programming Code Analytics",
    "Programming Language",
    "Programming Paradigm",
    "Project Management",
    "Prolog",
    "Prometheus",
    "Propagation Delay",
    "Propositional Calculus",
    "Prosthesis",
    "Protractor",
    "Proximity Search",
    "Publishing",
    "Pubnub",
    "Pug",
    "Pulp And Paper industry",
    "Pulse Signal Processing",
    "Puma",
    "Puppet Labs",
    "Puppeteer",
    "Push Monkey",
    "Pushdown Automaton",
    "Pusher",
    "Pushwoosh",
    "Pwa",
    "Pycharm",
    "Python",
    "Pytorch",
    "Qt",
    "Quality Of Service",
    "Quantifier Elimination",
    "Quantization Signal Processing",
    "Quantum Algorithm",
    "Quantum Computer",
    "Query Expansion",
    "Query Language",
    "Query Languages",
    "Query Optimization",
    "Query String",
    "Question Answering",
    "Queue",
    "Queueing Theory",
    "Qunit",
    "r",
    "Rabbitmq",
    "Rackspace Cloud Servers",
    "Rails",
    "Rails Api",
    "Raml",
    "Rancher",
    "Random Access",
    "Random Effects Model",
    "Random Forest",
    "Random Indexing",
    "Random Projection",
    "Range Query Data structures",
    "Ranking",
    "Raspberry Pi",
    "Ratchet",
    "Rdf",
    "Reachability",
    "React",
    "React Hot Loader",
    "React Native",
    "React Navigation",
    "React Router",
    "React Storybook",
    "React.Js Boilerplate",
    "Reactiveui",
    "Read Only Memory",
    "Read Write Memory",
    "Readme.Io",
    "Real Time Communication",
    "Real Time Computing",
    "Real Time Data",
    "Real Time Data processing",
    "Real Time Operating system",
    "Realm",
    "Realtime Analytics",
    "Realtime Backend Api",
    "Receiver Operating Characteristic",
    "Recommender System",
    "Record Linkage",
    "Recurly",
    "Recursion",
    "Redash",
    "Redis",
    "Redis Cloud",
    "Redis Hosting",
    "Redmine",
    "Redundancy Engineering",
    "Redux",
    "Redux Saga",
    "Redux Thunk",
    "Redux.Js",
    "Reference Frame",
    "Region Of Interest",
    "Regression Analysis",
    "Regular Expression",
    "Regular Language",
    "Reinforcement Learning",
    "Relational Database",
    "Relative Record Data set",
    "Relay",
    "Release",
    "Reliability Computer Networking",
    "Reliability Engineering",
    "Remote Control",
    "Remote Procedure Call",
    "Remote Procedure Call rpc",
    "Replication Computing",
    "Requirejs",
    "Residual",
    "Resource Allocation",
    "Response Surface Methodology",
    "Response Time",
    "Resque",
    "Rest Api",
    "Result Set",
    "Rethinkdb",
    "Reverse Engineering",
    "Riak",
    "Riot",
    "Risk Analysis Engineering",
    "Robot",
    "Robustness Computer Science",
    "Rocket",
    "Rollbar",
    "Rotation",
    "Rough Set",
    "Round Trip Delay time",
    "Router",
    "Routing Protocol",
    "Rspec",
    "Rubocop",
    "Ruby",
    "Rubymine",
    "Rule Based System",
    "Rule Induction",
    "Rule Of Thumb",
    "Runscope",
    "Runtime System",
    "Rust",
    "Rxjs",
    "Sails.Js",
    "Salesforce Sales Cloud",
    "Sass",
    "Satisfiability",
    "Sauce Labs",
    "Scaffold",
    "Scala",
    "Scalability",
    "Scalable Vector Graphics",
    "Scale Space",
    "Scaleway",
    "Scanner",
    "Schedule",
    "Scheduling Computing",
    "Scientometrics",
    "Scikit Learn",
    "Screen Sharing",
    "Scripting Language",
    "Scrutinizer",
    "Sdn",
    "Search Algorithm",
    "Search As A service",
    "Search Box",
    "Search Engine",
    "Search Engine Indexing",
    "Search Engines",
    "Searchretrieve Via Url",
    "Seasonality",
    "Secret Sharing",
    "Secrets Management",
    "Secure Communication",
    "Secure Multi Party computation",
    "Security",
    "Seesaw",
    "Segment",
    "Segmentation",
    "Selenium",
    "Self Hosted Blogging cms",
    "Self Management",
    "Self Organization",
    "Semantic Computing",
    "Semantic Data Model",
    "Semantic Html",
    "Semantic Matching",
    "Semantic Network",
    "Semantic Similarity",
    "Semantic Ui",
    "Semantic Ui React",
    "Semantic Web",
    "Semantic Web Stack",
    "Semantics",
    "Semaphore",
    "Semi Supervised Learning",
    "Sencha Touch",
    "Sendbird",
    "Sendgrid",
    "Sendwithus",
    "Sensor Array",
    "Sensor Fusion",
    "Sensor Tower",
    "Sentiment Analysis",
    "Sentry",
    "Sequel Pro",
    "Sequelize",
    "Sequential Logic",
    "Sequential Pattern Mining",
    "Server",
    "Server Configuration And automation",
    "Serverless",
    "Serverless Task Processing",
    "Shape Analysis Digital geometry",
    "Shared Memory",
    "Shared Resource",
    "Shell",
    "Shields.Io",
    "Shift Register",
    "Shippable",
    "Shopify",
    "Shortest Path Problem",
    "Shrinkage",
    "Sidekiq",
    "Signal Processing",
    "Signal Strength",
    "Signalr",
    "Similarity Measure",
    "Simulated Annealing",
    "Simulation",
    "Sinatra",
    "Skeleton",
    "Skeleton Computer Programming",
    "Sketch",
    "Skype",
    "Slack",
    "Sliding Window Protocol",
    "Slim",
    "Slim Lang",
    "Sma",
    "Smart Card",
    "Smart Information Retrieval system",
    "Smoothing",
    "Snippet",
    "Snowflake",
    "Snyk",
    "Social Media Tools",
    "Socket.Io",
    "Softlayer",
    "Software",
    "Software Agent",
    "Software Defined Radio",
    "Software Engineering",
    "Solid Modeling",
    "Solr",
    "Sonar",
    "Sonarqube",
    "Sonatype Nexus",
    "Sorting",
    "Source Code",
    "Source Code Management desktop apps",
    "Source Document",
    "Source Separation",
    "Sourcetree",
    "Spacemacs",
    "Spacevim",
    "Sparkpost",
    "Sparse Approximation",
    "Spatial Analysis",
    "Spatial Frequency",
    "Speaker Recognition",
    "Specification",
    "Specification Language",
    "Speckle Pattern",
    "Spectrogram",
    "Speech Coding",
    "Speech Processing",
    "Speech Recognition",
    "Sphinx",
    "Spread Spectrum",
    "Spreadsheets As A backend",
    "Spreadsheets Online",
    "Spree",
    "Spring",
    "Spring Boot",
    "Spring Cloud",
    "Sql",
    "Sql Database As a service",
    "Sqlalchemy",
    "Sqlite",
    "Squarespace",
    "Stack Overflow",
    "Stackdriver",
    "Stamplay",
    "Standard Ml",
    "Stars",
    "State Diagram",
    "State Management Library",
    "Static Random Access memory",
    "Static Site Generators",
    "Static Timing Analysis",
    "Static Web Hosting",
    "Statistical Classification",
    "Statistical Model",
    "Status Page Hosting",
    "Statuscake",
    "Stemming",
    "Stereopsis",
    "Stitch",
    "Stop Words",
    "Storm",
    "Storybook",
    "Stream Processing",
    "Streams",
    "Stripe",
    "Strips",
    "Strongly Connected Component",
    "Structural Engineering",
    "Structural Equation Modeling",
    "Structured Document",
    "Structured Text",
    "Styled Components",
    "Stylelint",
    "Stylus",
    "Subject Access",
    "Sublime Text",
    "Supercomputer",
    "Superresolution",
    "Superset",
    "Supervised Learning",
    "Supervisory Control",
    "Support",
    "Support Sales And marketing",
    "Support Vector Machine",
    "Surge",
    "Survey Widget",
    "Svn Subversion",
    "Swagger Ui",
    "Swift",
    "Swiftype",
    "Symfony",
    "Symmetric Multiprocessor System",
    "Synchronization",
    "Syntax",
    "Synthetic Aperture Radar",
    "Synthetic Data",
    "System Integration",
    "System On A chip",
    "System Testing",
    "Systems Engineering",
    "Systems Management",
    "Table Information",
    "Tableau",
    "Tabu Search",
    "Tailwind Css",
    "Task Management",
    "Teamcity",
    "Technological Change",
    "Telecommunications",
    "Telecommunications Network",
    "Telecommunications Service",
    "Telegram",
    "Telegram Bot Api",
    "Telephony",
    "Template Matching",
    "Templating Languages Extensions",
    "Temporal Database",
    "Tensorflow",
    "Terminal",
    "Terraform",
    "Testflight",
    "Testing",
    "Testing Frameworks",
    "Text Box",
    "Text Editor",
    "Text Mining",
    "Text Processing",
    "Text Retrieval Conference",
    "Text Segmentation",
    "Textmate",
    "Tfidf",
    "Theoretical Computer Science",
    "Thread Computing",
    "Thresholding",
    "Throughput",
    "Time Constraint",
    "Time Domain",
    "Time Of Arrival",
    "Time Series",
    "Time Sharing",
    "Time To Market",
    "Time Tracking",
    "Timefrequency Analysis",
    "Title Search",
    "Tools For Github",
    "Tools For Text editors",
    "Top Down And bottom up design",
    "Topic Maps",
    "Topic Model",
    "Tornado",
    "Tower",
    "Tracking System",
    "Traefik",
    "Traffic Engineering",
    "Traffic Model",
    "Training Set",
    "Transactional Email",
    "Transition System",
    "Translation Service",
    "Transparency Graphic",
    "Transport Engineering",
    "Transport Layer",
    "Travelling Salesman Problem",
    "Travis Ci",
    "Trecvid",
    "Tree Automaton",
    "Tree Data Structure",
    "Tree Structure",
    "Trello",
    "Trend Analysis",
    "Triangulation Social Science",
    "Turing Machine",
    "Twilio",
    "Twitter",
    "Type Inference",
    "Type Theory",
    "Typeform",
    "Typescript",
    "Ubiquitous Computing",
    "Ubuntu",
    "Uglifyjs",
    "Uikit",
    "Uncertain Data",
    "Underscore",
    "Unicorn",
    "Unified Medical Language system",
    "Unified Modeling Language",
    "Unity",
    "Unreal Engine",
    "Unsupervised Learning",
    "Uppy",
    "Uptime Robot",
    "Urban Airship",
    "User Feedback As a service",
    "User Interface",
    "User Management And authentication",
    "User Profile",
    "Utilities",
    "Vagrant",
    "Variables",
    "Varnish",
    "Vault",
    "Vector Space Model",
    "Version Control System",
    "Very Large Database",
    "Video Processing",
    "Video Quality",
    "Video Tracking",
    "Vim",
    "Virtual Circuit",
    "Virtual Machine",
    "Virtual Machine Management",
    "Virtual Machine Platforms containers",
    "Virtual Memory",
    "Virtual Organization",
    "Virtual Private Cloud",
    "Virtual Reality",
    "Virtualbox",
    "Virtualization Platform",
    "Visual Basic",
    "Visual Cortex",
    "Visual Inspection",
    "Visual Programming Language",
    "Visual Studio",
    "Visual Studio Code",
    "Visual Studio Team services",
    "Visualization",
    "Viterbi Algorithm",
    "Vmware Vsphere",
    "Voice And Sms",
    "Voice Over Ip",
    "Vue",
    "Vue.Js",
    "Vuepress",
    "Vuetify",
    "Vuex",
    "Wagtail",
    "Wakatime",
    "Waste Management",
    "Watershed",
    "Wavefront",
    "Wavelength Division Multiplexing",
    "Wavelet",
    "Web And Video conferencing",
    "Web App Builders",
    "Web Components",
    "Web Crawler",
    "Web Document",
    "Web Forms",
    "Web Mining",
    "Web Server",
    "Web Servers",
    "Web Service",
    "Web Service Automation",
    "Web Starter Kit",
    "Webapp",
    "Webflow",
    "Webpack",
    "Website Builder",
    "Website Monitoring",
    "Webstorm",
    "Weebly",
    "Wercker",
    "Wide Area Network",
    "Wiener Filter",
    "Wimax",
    "Windows",
    "Wireframing",
    "Wireless",
    "Wireless Ad Hoc network",
    "Wireless Network",
    "Wireless Sensor Network",
    "Wix",
    "Woocommerce",
    "Woopra",
    "Word Error Rate",
    "Word Sense Disambiguation",
    "Wordnet",
    "Wordplate",
    "Wordpress",
    "Workflow",
    "Workflow Manager",
    "Workload",
    "World Wide Web",
    "Xamarin",
    "Xcode",
    "Xml",
    "Yarn",
    "Yeoman",
    "Yii",
    "Zend Framework",
    "Zendesk",
    "Zenefits",
    "Zeplin",
    "Zepto",
    "Zeromq",
    "Zoho Crm",
    "Zookeeper",
]
module.exports.autoSuggestion = autoSuggestion;